# external-secret-for-extenal-dns
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dev-external-dns-cloudflare-api-token
  namespace: external-dns
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-dev-parameter-store
  target:
    name: dev-external-dns-cloudflare-api-token
    deletionPolicy: Delete
  data:
    - secretKey: apiKey
      remoteRef:
        key: /account-configuration/dev/doks-external-dns-cloudflare-token
